const SCRAP_DATA = {
  ferrous: {
    id: 'ferrous',
    label: 'Ferrous Metal',
    sublabel: 'Iron & Steel Alloys',
    accent: '#60A5FA',
    dim: 'rgba(96,165,250,0.1)',
    border: 'rgba(96,165,250,0.3)',
    glow: 'rgba(96,165,250,0.15)',
    tags: ['Magnetic', 'High Demand', 'EAF Ready'],
    description:
      'Iron and steel-based scrap — the most recycled material on the planet. Strongly magnetic, endlessly recyclable through electric arc or blast furnace processing with major energy savings over virgin production.',
    stats: [
      {
        label: 'Market Value',
        value: '₹18–25',
        unit: '/kg',
        note: 'HMS1 grade',
      },
      {
        label: 'Recyclability',
        value: '100%',
        unit: '',
        note: 'Infinite cycles',
      },
      {
        label: 'CO₂ Saved',
        value: '1.5T',
        unit: '/tonne',
        note: 'vs virgin steel',
      },
      { label: 'Global Share', value: '47%', unit: '', note: 'Most recycled' },
    ],
    properties: [
      'Strongly magnetic — drum separator compatible',
      'Tensile strength 400–550 MPa',
      'Melting point 1370–1540°C',
      'Susceptible to surface rust and oxidation',
      'Grades: HMS1 · HMS2 · Shredded · Cast Iron',
    ],
    handling: [
      'Visual inspection + magnet test for grade sort',
      'Remove all non-ferrous attachments',
      'Strip paint, coatings and oil contamination',
      'Shred or bale to transport specification',
      'Feed directly to EAF or blast furnace',
    ],
    useCases: [
      'Structural steel beams',
      'Rebar for construction',
      'Automotive body panels',
      'Machinery components',
    ],
    hazard: null,
    keywords: [
      'nail',
      'screw',
      'bolt',
      'wrench',
      'iron',
      'steel',
      'file',
      'knife',
      'shovel',
      'padlock',
      'lock',
      'radiator',
      'gear',
      'wheel',
      'axle',
      'hammer',
      'beam',
      'girder',
      'rust',
      'crowbar',
      'anvil',
    ],

    // ── 8 NEW METALLURGICAL DATA FIELDS ──────────────────────────────
    phase: {
      title: 'Fe-C Phase Diagram',
      system: 'Iron-Carbon (Fe-C)',
      region: 'Hypoeutectoid',
      carbonRange: '0.02 – 0.77% C',
      eutectoidPoint: '0.77% C · 723°C',
      phases: [
        'Ferrite (α-Fe)',
        'Pearlite (α+Fe₃C)',
        'Austenite (γ-Fe) at temp',
      ],
      note: 'Steel scrap lies in the hypoeutectoid region. At room temperature, microstructure is ferrite + pearlite. Austenite forms above 723°C (A1 line).',
      tempLines: [
        { label: 'A1 (Eutectoid)', temp: 723, note: 'Pearlite ↔ Austenite' },
        { label: 'A3 (Upper)', temp: 910, note: 'Full austenite zone' },
        { label: 'Solidus', temp: 1370, note: 'Starts melting' },
        { label: 'Liquidus', temp: 1540, note: 'Fully liquid' },
      ],
    },
    microstructure: {
      dominant: 'Pearlite + Ferrite',
      likely: [
        'Pearlite + Ferrite (mild steel, HMS)',
        'Bainite (low-alloy quenched)',
        'Martensite (hardened tool steel)',
        'Widmanstätten ferrite (cast iron)',
      ],
      grainSize: 'ASTM 6–8',
      hardness: '120–200 HB (Brinell)',
      note: 'Ferrite is soft BCC phase. Pearlite is lamellar mix of ferrite + cementite (Fe₃C). Proportion determines strength and recyclability grade.',
    },
    thermalWindow: {
      unit: '°C',
      zones: [
        { label: 'Preheat / Dry-out', temp: 150, pct: 8, color: '#fbbf24' },
        { label: 'A1 Eutectoid', temp: 723, pct: 38, color: '#f97316' },
        { label: 'Solidus', temp: 1370, pct: 72, color: '#ef4444' },
        { label: 'Liquidus', temp: 1540, pct: 82, color: '#dc2626' },
        { label: 'EAF Tap Temp', temp: 1620, pct: 88, color: '#b91c1c' },
      ],
      note: 'EAF tapping temperature 1580–1640°C. Superheat of 40–80°C above liquidus ensures complete melt and slag separation.',
    },
    composition: [
      {
        element: 'Fe',
        pct: 97.5,
        range: '95–99%',
        color: '#60A5FA',
        note: 'Base metal',
      },
      {
        element: 'C',
        pct: 0.25,
        range: '0.02–2.1%',
        color: '#34d399',
        note: 'Strength/hardness',
      },
      {
        element: 'Mn',
        pct: 0.8,
        range: '0.3–1.8%',
        color: '#F472B6',
        note: 'Deoxidizer',
      },
      {
        element: 'Si',
        pct: 0.25,
        range: '0.1–0.6%',
        color: '#FB923C',
        note: 'Deoxidizer',
      },
      {
        element: 'P+S',
        pct: 0.05,
        range: '<0.05%',
        color: '#a78bfa',
        note: 'Tramp elements',
      },
    ],
    furnaceCompat: [
      {
        name: 'Electric Arc Furnace (EAF)',
        compat: 'excellent',
        note: 'Primary route — 100% scrap charge possible',
      },
      {
        name: 'Basic Oxygen Furnace (BOF)',
        compat: 'good',
        note: 'Up to 30% scrap in hot metal charge',
      },
      {
        name: 'Induction Furnace',
        compat: 'good',
        note: 'For cast iron and alloy grades',
      },
      {
        name: 'Blast Furnace',
        compat: 'limited',
        note: 'Only as coolant, not primary charge',
      },
      {
        name: 'Cupola Furnace',
        compat: 'good',
        note: 'For grey and ductile iron scrap',
      },
    ],
    contamination: [
      {
        contaminant: 'Copper (Cu)',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Hot shortness — embrittles steel at 1100°C, causes surface cracking during hot rolling. 0.1% Cu is threshold.',
      },
      {
        contaminant: 'Tin (Sn)',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Reduces hot ductility. Causes "terne" surface defects. Enters from coated steel cans.',
      },
      {
        contaminant: 'Zinc (Zn)',
        risk: 'HIGH',
        color: '#f97316',
        effect:
          'Fuming at 907°C — destroys EAF refractory lining and generates ZnO fumes requiring bag filtration.',
      },
      {
        contaminant: 'Lead (Pb)',
        risk: 'CRITICAL',
        color: '#dc2626',
        effect:
          'Collects at furnace bottom (density 11.3 g/cm³). Attacks refractory, carcinogenic fume, worker health hazard.',
      },
    ],
    grades: [
      {
        grade: 'HMS 1',
        desc: 'Heavy Melting Steel >6mm, clean uncoated',
        value: '₹22–25/kg',
        quality: 95,
      },
      {
        grade: 'Bushelling',
        desc: 'Clean stampings <6mm, no coating',
        value: '₹23–26/kg',
        quality: 92,
      },
      {
        grade: 'HMS 2',
        desc: 'Heavy Melting Steel 3–6mm, mixed',
        value: '₹20–22/kg',
        quality: 78,
      },
      {
        grade: 'Shredded',
        desc: 'Auto bodies, white goods, shredded',
        value: '₹18–20/kg',
        quality: 68,
      },
      {
        grade: 'Cast Iron',
        desc: 'Engine blocks, machine beds',
        value: '₹16–18/kg',
        quality: 55,
      },
    ],
    standards: [
      {
        code: 'IS 2102',
        body: 'BIS',
        desc: 'Steel scrap classification and grading',
      },
      { code: 'IS 1875', body: 'BIS', desc: 'Steel billets, blooms and slabs' },
      { code: 'ASTM E415', body: 'ASTM', desc: 'OES analysis of steel' },
      {
        code: 'HMS 1&2',
        body: 'ISRI',
        desc: 'Heavy melting scrap grade definitions',
      },
    ],
    carbonCalc: {
      co2PerTonne: 1.5,
      energyPerTonne: 630,
      waterPerTonne: 40,
      treesEquiv: 68,
    },
  },

  nonferrous: {
    id: 'nonferrous',
    label: 'Non-Ferrous Metal',
    sublabel: 'Copper · Aluminium · Alloys',
    accent: '#34D399',
    dim: 'rgba(52,211,153,0.1)',
    border: 'rgba(52,211,153,0.3)',
    glow: 'rgba(52,211,153,0.15)',
    tags: ['High Value', 'Non-Magnetic', 'Conductor Grade'],
    description:
      'Copper, aluminium, brass and bronze scrap. Non-magnetic with significantly higher market value than ferrous. Critical for electrical infrastructure, EV batteries and renewable energy systems.',
    stats: [
      {
        label: 'Market Value',
        value: '₹80–400',
        unit: '/kg',
        note: 'Grade dependent',
      },
      {
        label: 'Recyclability',
        value: '100%',
        unit: '',
        note: 'No property loss',
      },
      {
        label: 'CO₂ Saved',
        value: '9.5T',
        unit: '/tonne',
        note: 'vs virgin Al/Cu',
      },
      {
        label: 'Conductivity',
        value: 'High',
        unit: '',
        note: 'Electrical grade',
      },
    ],
    properties: [
      'Non-magnetic — eddy current separation required',
      'High electrical and thermal conductivity',
      'Corrosion resistant — long service life',
      'Melting point 660–1085°C (Al to Cu)',
      'Recovery value: Copper > Brass > Aluminium',
    ],
    handling: [
      'XRF spectrometer verification of alloy grade',
      'Physically separate by metal type (Cu/Al/Brass)',
      'Strip all cable insulation and rubber jacketing',
      'Clean and decontaminate surface oils',
      'Melt in induction or reverberatory furnace',
    ],
    useCases: [
      'Electrical wiring',
      'Heat exchangers',
      'Plumbing fittings',
      'Automotive radiators',
    ],
    hazard: null,
    keywords: [
      'wire',
      'cable',
      'copper',
      'brass',
      'bronze',
      'aluminum',
      'pitcher',
      'ladle',
      'wok',
      'strainer',
      'tube',
      'chain',
      'hook',
      'coil',
      'ring',
      'loop',
      'bangle',
      'reel',
      'spool',
      'mesh',
      'filament',
      'pot',
      'pan',
      'bowl',
      'spoon',
      'fork',
    ],

    phase: {
      title: 'Cu-Zn Phase Diagram (Brass)',
      system: 'Copper-Zinc (Cu-Zn) / Pure Cu',
      region: 'Alpha-phase (α-brass) / FCC Cu',
      carbonRange: '0–40% Zn (α-phase)',
      eutectoidPoint: 'Peritectic at 902°C (36% Zn)',
      phases: [
        'α-Cu (FCC, ductile)',
        'α+β duplex (30–45% Zn)',
        'β-brass (CsCl structure)',
      ],
      note: 'Pure copper is FCC, highly ductile. α-brass (Cu-Zn <35%) is single phase, excellent cold workability. β-phase reduces ductility but improves strength.',
      tempLines: [
        { label: 'Al Melting', temp: 660, note: 'Pure aluminium' },
        { label: 'Brass Solidus', temp: 900, note: 'Cu-40Zn alloy' },
        { label: 'Cu Melting', temp: 1085, note: 'Pure copper' },
        { label: 'Processing', temp: 1150, note: 'Induction furnace' },
      ],
    },
    microstructure: {
      dominant: 'FCC equiaxed grains (Cu) / Dendritic (cast)',
      likely: [
        'Equiaxed FCC grains (annealed copper wire)',
        'Elongated grains (cold-drawn cable)',
        'Dendritic as-cast structure (copper ingot)',
        'Lamellar α+β (high-zinc brass)',
      ],
      grainSize: 'ASTM 4–7',
      hardness: '35–120 HB (Cu to brass)',
      note: 'Copper FCC structure gives excellent ductility. Grain refinement via cold working increases strength. Recrystallization occurs at 200–300°C for Cu.',
    },
    thermalWindow: {
      unit: '°C',
      zones: [
        { label: 'Al Melting', temp: 660, pct: 38, color: '#fbbf24' },
        { label: 'Brass Liquidus', temp: 940, pct: 55, color: '#f97316' },
        { label: 'Cu Solidus', temp: 1085, pct: 63, color: '#ef4444' },
        { label: 'Induction Tap', temp: 1150, pct: 67, color: '#dc2626' },
        { label: 'Cu Superheated', temp: 1200, pct: 70, color: '#b91c1c' },
      ],
      note: 'Aluminium requires separate low-temperature processing at 720–760°C. Mixing Cu and Al creates brittle intermetallic CuAl₂ — always segregate.',
    },
    composition: [
      {
        element: 'Cu',
        pct: 99.9,
        range: '99–99.9%',
        color: '#34D399',
        note: 'Primary metal (wire)',
      },
      {
        element: 'Zn',
        pct: 30,
        range: '0–40%',
        color: '#60A5FA',
        note: 'Brass alloying',
      },
      {
        element: 'Sn',
        pct: 8,
        range: '0–12%',
        color: '#F472B6',
        note: 'Bronze alloying',
      },
      {
        element: 'Pb',
        pct: 2,
        range: '0–3%',
        color: '#ef4444',
        note: 'Free-machining',
      },
      {
        element: 'Fe',
        pct: 0.05,
        range: '<0.1%',
        color: '#a78bfa',
        note: 'Tramp impurity',
      },
    ],
    furnaceCompat: [
      {
        name: 'Induction Furnace',
        compat: 'excellent',
        note: 'Primary route — precise temperature control',
      },
      {
        name: 'Reverberatory Furnace',
        compat: 'excellent',
        note: 'For bulk Al/Cu smelting',
      },
      {
        name: 'Rotary Furnace',
        compat: 'good',
        note: 'For mixed non-ferrous charge',
      },
      {
        name: 'Electric Arc Furnace (EAF)',
        compat: 'none',
        note: 'NEVER — copper destroys steel quality',
      },
      {
        name: 'Blast Furnace',
        compat: 'none',
        note: 'Not suitable for non-ferrous',
      },
    ],
    contamination: [
      {
        contaminant: 'Iron (Fe)',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Reduces electrical conductivity below IACS specification. Even 0.1% Fe drops conductivity by 15%.',
      },
      {
        contaminant: 'Aluminium in Cu',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Forms brittle CuAl₂ intermetallic. Causes catastrophic embrittlement — makes wire unworkable.',
      },
      {
        contaminant: 'Lead (Pb)',
        risk: 'MEDIUM',
        color: '#f97316',
        effect:
          'Worker health hazard during melting. Fume extraction mandatory. Low threshold — 5μg/m³ TLV.',
      },
      {
        contaminant: 'PVC Insulation',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Releases HCl gas above 150°C. Corrodes furnace lining and pollutes metal with chlorides.',
      },
    ],
    grades: [
      {
        grade: '#1 Copper (Birch)',
        desc: 'Clean bare bright copper wire, >99.9%',
        value: '₹380–420/kg',
        quality: 100,
      },
      {
        grade: '#2 Copper (Cliff)',
        desc: 'Copper pipe/wire, may have solder',
        value: '₹320–360/kg',
        quality: 82,
      },
      {
        grade: 'Berry (Insulated)',
        desc: 'Copper cable with insulation attached',
        value: '₹180–220/kg',
        quality: 55,
      },
      {
        grade: 'Brass (Honey)',
        desc: 'Clean yellow brass, no iron',
        value: '₹200–260/kg',
        quality: 65,
      },
      {
        grade: 'Aluminium #1',
        desc: 'Clean Al extrusions, no paint',
        value: '₹100–130/kg',
        quality: 72,
      },
    ],
    standards: [
      {
        code: 'IS 613',
        body: 'BIS',
        desc: 'Copper rods and bars for electrical purposes',
      },
      {
        code: 'IS 736',
        body: 'BIS',
        desc: 'Wrought aluminium alloy specification',
      },
      { code: 'ASTM B5', body: 'ASTM', desc: 'High conductivity copper rod' },
      {
        code: 'ISRI 200',
        body: 'ISRI',
        desc: 'Scrap specifications circular — non-ferrous',
      },
    ],
    carbonCalc: {
      co2PerTonne: 9.5,
      energyPerTonne: 14000,
      waterPerTonne: 70,
      treesEquiv: 432,
    },
  },

  ewaste: {
    id: 'ewaste',
    label: 'Electronic Scrap',
    sublabel: 'E-Waste & PCB Materials',
    accent: '#F472B6',
    dim: 'rgba(244,114,182,0.1)',
    border: 'rgba(244,114,182,0.3)',
    glow: 'rgba(244,114,182,0.15)',
    tags: ['Precious Metals', 'Hazardous', 'Regulated'],
    description:
      'Electronic waste containing recoverable precious metals — gold, silver, palladium — alongside hazardous lead, mercury and cadmium. Regulated under E-Waste (Management) Rules 2022. Certified processing mandatory.',
    stats: [
      {
        label: 'Market Value',
        value: '₹20–150',
        unit: '/kg',
        note: 'PCB grade',
      },
      {
        label: 'Precious Metals',
        value: 'Au+Ag+Pd',
        unit: '',
        note: 'Recoverable',
      },
      { label: 'Hazard Level', value: 'HIGH', unit: '', note: 'Pb · Hg · Cd' },
      {
        label: 'Legal Class',
        value: 'Regulated',
        unit: '',
        note: 'E-Waste Rules 2022',
      },
    ],
    properties: [
      'Gold, silver, palladium on PCB traces',
      'Lead solder, mercury switches, cadmium cells',
      'Mixed: PCB + metal + polymer composition',
      'Urban mining yield 200–800g Au per tonne',
      'MoEFCC authorization mandatory to process',
    ],
    handling: [
      'Wear PPE — nitrile gloves + N95 mask mandatory',
      'Remove and segregate all battery types first',
      'Manually extract PCBs from metal chassis',
      'Separate and coil copper cables independently',
      'Route to MoEFCC-authorized dismantler only',
    ],
    useCases: [
      'Gold recovery from PCBs',
      'Copper cable reuse',
      'Aluminium chassis recycling',
      'Palladium catalyst recovery',
    ],
    hazard: {
      level: 'HIGH',
      message:
        'Contains lead (Pb), mercury (Hg) and cadmium (Cd). Illegal to landfill under E-Waste (Management) Rules 2022. Do NOT incinerate — releases carcinogenic dioxins and furans.',
    },
    keywords: [
      'computer',
      'laptop',
      'keyboard',
      'mouse',
      'monitor',
      'screen',
      'television',
      'phone',
      'printer',
      'circuit',
      'hard disk',
      'cd',
      'dvd',
      'modem',
      'router',
      'remote',
      'camera',
      'calculator',
    ],

    phase: {
      title: 'Urban Mining Phase Map',
      system: 'Multi-Metal E-Waste Matrix',
      region: 'Heterogeneous multi-phase composite',
      carbonRange: '200–800 g Au per tonne PCB',
      eutectoidPoint: 'Pb-Sn eutectic at 183°C (solder)',
      phases: [
        'Cu matrix (PCB traces)',
        'Pb-Sn solder (eutectic)',
        'FR4 epoxy polymer substrate',
        'Precious metal plating (Au, Ag, Pd)',
      ],
      note: 'PCB is a complex multi-phase system. Hydrometallurgical or pyrometallurgical routes used for precious metal recovery. Gold concentration 40–800× higher than gold ore.',
      tempLines: [
        {
          label: 'Pb-Sn Eutectic',
          temp: 183,
          note: 'Solder melts — reflow possible',
        },
        { label: 'FR4 Decompose', temp: 340, note: 'Epoxy substrate degrades' },
        { label: 'Cu Melting', temp: 1085, note: 'Copper traces melt' },
        { label: 'Smelting', temp: 1250, note: 'Pyrometallurgical processing' },
      ],
    },
    microstructure: {
      dominant: 'Pb-Sn eutectic solder + Cu intermetallics',
      likely: [
        'Cu₆Sn₅ intermetallic at solder joints',
        'Gold flash on Cu (0.1–1μm)',
        'Palladium on connector contacts',
        'Lead-tin eutectic matrix (solder balls)',
      ],
      grainSize: 'N/A (composite)',
      hardness: '5–15 HB (solder) to 35 HB (Cu traces)',
      note: 'Au plating thickness 0.05–1.27μm on contacts. Cu₃Sn and Cu₆Sn₅ intermetallics form at solder-pad interface — causes joint embrittlement in aged boards.',
    },
    thermalWindow: {
      unit: '°C',
      zones: [
        { label: 'Pb-Sn Reflow', temp: 183, pct: 12, color: '#fbbf24' },
        { label: 'Pb-free Reflow', temp: 217, pct: 14, color: '#f97316' },
        { label: 'FR4 Degrade', temp: 340, pct: 22, color: '#ef4444' },
        { label: 'Cu Melt', temp: 1085, pct: 68, color: '#dc2626' },
        { label: 'Pyrometallurgy', temp: 1300, pct: 82, color: '#b91c1c' },
      ],
      note: 'Never incinerate below 850°C — incomplete combustion forms dioxins/furans (PCDD/PCDF). High-temperature smelting at 1200°C+ required for safe destruction of brominated flame retardants.',
    },
    composition: [
      {
        element: 'Fe',
        pct: 20,
        range: '15–25%',
        color: '#60A5FA',
        note: 'Steel chassis',
      },
      {
        element: 'Cu',
        pct: 7,
        range: '5–10%',
        color: '#34D399',
        note: 'PCB traces, cables',
      },
      {
        element: 'Al',
        pct: 14,
        range: '10–18%',
        color: '#fbbf24',
        note: 'Heatsinks, frame',
      },
      {
        element: 'Pb',
        pct: 4,
        range: '2–6%',
        color: '#ef4444',
        note: 'Solder, CRT glass',
      },
      {
        element: 'Au',
        pct: 0.03,
        range: '0.01–0.1%',
        color: '#FB923C',
        note: 'PCB contacts',
      },
    ],
    furnaceCompat: [
      {
        name: 'Specialized E-Waste Smelter',
        compat: 'excellent',
        note: 'UMICORE/Boliden-type — precious metal recovery',
      },
      {
        name: 'Hydromet Plant',
        compat: 'excellent',
        note: 'Acid leach + electrowinning for Au/Ag/Pd',
      },
      {
        name: 'Induction Furnace (Cu)',
        compat: 'limited',
        note: 'Only for clean Cu chassis — no PCBs',
      },
      {
        name: 'Electric Arc Furnace (EAF)',
        compat: 'none',
        note: 'Destroys precious metals, toxic fumes',
      },
      {
        name: 'Municipal Incinerator',
        compat: 'none',
        note: 'ILLEGAL — dioxin/furan emissions, MoEFCC ban',
      },
    ],
    contamination: [
      {
        contaminant: 'Brominated Flame Retardants',
        risk: 'CRITICAL',
        color: '#dc2626',
        effect:
          'Forms PBDD/PBDF dioxins above 300°C. Persistent organic pollutants — bioaccumulate in food chain.',
      },
      {
        contaminant: 'Mercury (Hg)',
        risk: 'CRITICAL',
        color: '#dc2626',
        effect:
          'From CCFL backlights and switches. Vapour toxic at room temperature — 0.025 mg/m³ TLV.',
      },
      {
        contaminant: 'Cadmium (Cd)',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'In NiCd batteries — carcinogenic. Accumulates in kidneys. Basel Convention restricted.',
      },
      {
        contaminant: 'Beryllium (Be)',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'In connectors and springs — causes berylliosis (fatal lung disease). Dust extremely dangerous.',
      },
    ],
    grades: [
      {
        grade: 'Grade A PCB',
        desc: 'Server/telecom boards, high gold content',
        value: '₹120–180/kg',
        quality: 100,
      },
      {
        grade: 'Grade B PCB',
        desc: 'Desktop/laptop boards, medium gold',
        value: '₹60–100/kg',
        quality: 70,
      },
      {
        grade: 'Mixed Boards',
        desc: 'Consumer electronics, low precious metal',
        value: '₹20–50/kg',
        quality: 40,
      },
      {
        grade: 'CPU/GPU chips',
        desc: 'Processors — highest Au concentration',
        value: '₹200–500/kg',
        quality: 100,
      },
      {
        grade: 'Cable scrap',
        desc: 'Mixed copper cable, insulated',
        value: '₹30–80/kg',
        quality: 45,
      },
    ],
    standards: [
      {
        code: 'E-Waste Rules 2022',
        body: 'MoEFCC',
        desc: 'Mandatory EPR and authorized dismantler',
      },
      { code: 'IS 16270', body: 'BIS', desc: 'E-waste management guidelines' },
      {
        code: 'Basel Convention',
        body: 'UN',
        desc: 'Transboundary movement of hazardous waste',
      },
      {
        code: 'RoHS Directive',
        body: 'EU',
        desc: 'Restriction of hazardous substances',
      },
    ],
    carbonCalc: {
      co2PerTonne: 2.0,
      energyPerTonne: 4200,
      waterPerTonne: 25,
      treesEquiv: 91,
    },
  },

  plastic: {
    id: 'plastic',
    label: 'Plastic / Polymer',
    sublabel: 'Mixed Polymer Waste Stream',
    accent: '#FB923C',
    dim: 'rgba(251,146,60,0.1)',
    border: 'rgba(251,146,60,0.3)',
    glow: 'rgba(251,146,60,0.15)',
    tags: ['Furnace Risk', 'Segregate First', 'Polymer Grade'],
    description:
      'Polymer-based waste contaminating metal scrap streams. Must be fully removed before furnace processing — thermal breakdown releases toxic gases and destroys furnace linings. Route to polymer-specific recyclers.',
    stats: [
      {
        label: 'Market Value',
        value: '₹5–25',
        unit: '/kg',
        note: 'Polymer type dep.',
      },
      {
        label: 'Recyclability',
        value: 'Limited',
        unit: '',
        note: 'Type-specific only',
      },
      {
        label: 'Furnace Risk',
        value: 'CRITICAL',
        unit: '',
        note: 'Never co-process',
      },
      {
        label: 'CO₂ Saved',
        value: '1.8T',
        unit: '/tonne',
        note: 'vs virgin polymer',
      },
    ],
    properties: [
      'Non-conductive, low density material',
      'Types: PET · PVC · HDPE · PP · PS',
      'PVC releases toxic HCl gas above 150°C',
      'Contaminates metal melt — reduces yield',
      'Resin code (1–7) stamped on most items',
    ],
    handling: [
      'Remove from metal stream immediately on receipt',
      'Identify polymer via resin code or burn test',
      'Strictly isolate PVC from PET/HDPE streams',
      'Bale and label clearly by polymer resin type',
      'Route to dedicated polymer recycling facility',
    ],
    useCases: [
      'Recycled PET bottles',
      'HDPE pipe manufacture',
      'Plastic lumber boards',
      'Packaging pellets',
    ],
    hazard: {
      level: 'MEDIUM',
      message:
        'PVC releases hydrogen chloride (HCl) gas when heated above 150°C. Never co-process with metal scrap or incinerate in mixed loads.',
    },
    keywords: [
      'bottle',
      'plastic',
      'bucket',
      'container',
      'barrel',
      'bag',
      'rubber',
      'pipe',
      'drum',
      'hose',
      'tray',
      'packaging',
      'foam',
      'polystyrene',
      'nylon',
    ],

    phase: {
      title: 'Polymer Identification Chart',
      system: 'Thermoplastic / Thermoset Matrix',
      region: 'Amorphous + Semi-crystalline',
      carbonRange: 'C₂H₄ (PE) to C₃H₃Cl (PVC)',
      eutectoidPoint: 'Glass transition Tg: -100°C to 100°C',
      phases: [
        'Amorphous regions (PET, PS, PVC)',
        'Crystalline lamellae (HDPE, PP)',
        'Tie molecules connecting phases',
        'Additive/filler dispersion phase',
      ],
      note: 'Semi-crystalline polymers (HDPE, PP) have both crystalline and amorphous regions. Degree of crystallinity determines stiffness and recyclability. PET is 0–60% crystalline.',
      tempLines: [
        { label: 'PVC Degrade (HCl)', temp: 150, note: 'HCl release starts' },
        { label: 'PP/HDPE Melt', temp: 165, note: 'Processing window' },
        { label: 'PET Melt', temp: 260, note: 'Injection moulding' },
        { label: 'Thermal Decompose', temp: 400, note: 'Pyrolysis begins' },
      ],
    },
    microstructure: {
      dominant: 'Spherulitic semi-crystalline structure',
      likely: [
        'Spherulitic crystalline (HDPE under polarized light)',
        'Amorphous entangled chains (atactic PS/PVC)',
        'Oriented fibrillar structure (drawn PET film)',
        'Foamed cellular structure (EPS/PP foam)',
      ],
      grainSize: 'Spherulite dia: 1–100μm',
      hardness: '50–120 Shore D',
      note: 'HDPE forms large spherulites — visible as Maltese cross under polarized light. PVC is amorphous — no crystalline structure. Crystallinity directly affects melting point and recyclability.',
    },
    thermalWindow: {
      unit: '°C',
      zones: [
        { label: 'PVC HCl Release', temp: 150, pct: 10, color: '#fbbf24' },
        { label: 'HDPE/PP Melt', temp: 165, pct: 11, color: '#f97316' },
        { label: 'PET Melt', temp: 260, pct: 17, color: '#ef4444' },
        { label: 'Pyrolysis Zone', temp: 400, pct: 26, color: '#dc2626' },
        { label: 'Full Combustion', temp: 600, pct: 39, color: '#b91c1c' },
      ],
      note: 'Plastics in EAF generate HCl (PVC), CO, CO₂, and benzene. Even 1% plastic in metal charge causes furnace lining damage and exceeds emission limits. Zero tolerance policy.',
    },
    composition: [
      {
        element: 'C',
        pct: 85,
        range: '75–92%',
        color: '#FB923C',
        note: 'Carbon backbone',
      },
      {
        element: 'H',
        pct: 14,
        range: '8–15%',
        color: '#fbbf24',
        note: 'Hydrogen',
      },
      {
        element: 'O',
        pct: 1,
        range: '0–32%',
        color: '#34d399',
        note: 'PET/nylon',
      },
      {
        element: 'Cl',
        pct: 0,
        range: '0–56%',
        color: '#ef4444',
        note: 'PVC only — toxic',
      },
      {
        element: 'N',
        pct: 0,
        range: '0–14%',
        color: '#a78bfa',
        note: 'Nylon/polyamide',
      },
    ],
    furnaceCompat: [
      {
        name: 'Polymer Extruder',
        compat: 'excellent',
        note: 'Pelletization for recycled resin production',
      },
      {
        name: 'Pyrolysis Reactor',
        compat: 'excellent',
        note: 'Chemical recycling → fuel oil + syngas',
      },
      {
        name: 'Co-processing (Cement Kiln)',
        compat: 'good',
        note: 'High CV plastics as fuel substitute',
      },
      {
        name: 'Electric Arc Furnace (EAF)',
        compat: 'none',
        note: 'STRICTLY FORBIDDEN — HCl destroys furnace',
      },
      {
        name: 'Induction Furnace',
        compat: 'none',
        note: 'No plastics — toxic gas generation',
      },
    ],
    contamination: [
      {
        contaminant: 'PVC in PET stream',
        risk: 'CRITICAL',
        color: '#dc2626',
        effect:
          'As little as 10 ppm PVC in PET causes HCl contamination, yellowing, and complete batch rejection.',
      },
      {
        contaminant: 'Metal fasteners',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'Damages extruder screws and barrels. Metal fragments in recycled pellets cause product failure.',
      },
      {
        contaminant: 'Food/organic waste',
        risk: 'MEDIUM',
        color: '#f97316',
        effect:
          'Causes mould growth in baled plastic. Generates H₂S and VOCs during processing. Reduces pellet quality.',
      },
      {
        contaminant: 'Multilayer films',
        risk: 'HIGH',
        color: '#ef4444',
        effect:
          'PE-PET-PA laminates cannot be separated — contaminate single-resin streams, reduce recyclate value to zero.',
      },
    ],
    grades: [
      {
        grade: 'PET (Code 1)',
        desc: 'Clear bottles, food grade, high demand',
        value: '₹18–25/kg',
        quality: 95,
      },
      {
        grade: 'HDPE (Code 2)',
        desc: 'Pipes, containers, industrial grade',
        value: '₹14–20/kg',
        quality: 85,
      },
      {
        grade: 'PP (Code 5)',
        desc: 'Caps, automotive, mixed colour',
        value: '₹10–15/kg',
        quality: 70,
      },
      {
        grade: 'PS (Code 6)',
        desc: 'Electronics housing, fragile',
        value: '₹6–10/kg',
        quality: 45,
      },
      {
        grade: 'PVC (Code 3)',
        desc: 'Pipes only — insulation separate',
        value: '₹5–8/kg',
        quality: 30,
      },
    ],
    standards: [
      {
        code: 'IS 14534',
        body: 'BIS',
        desc: 'Plastic waste management guidelines',
      },
      {
        code: 'PWM Rules 2016',
        body: 'CPCB',
        desc: 'Plastic Waste Management Rules India',
      },
      {
        code: 'ASTM D7611',
        body: 'ASTM',
        desc: 'Plastic resin identification codes',
      },
      {
        code: 'ISO 1043',
        body: 'ISO',
        desc: 'Plastics symbols and abbreviated terms',
      },
    ],
    carbonCalc: {
      co2PerTonne: 1.8,
      energyPerTonne: 5800,
      waterPerTonne: 20,
      treesEquiv: 82,
    },
  },
};
